" ----------------------------------------------------------------------------
"  ~/vimfiles/gvimrc
"
" config for when gvim is run
"
" Notes:
"     this is a really beautiful color! DeepSkyBlue4=#005f87
" ----------------------------------------------------------------------------

" prevents MacVim from applying its own colorscheme (see :h
" macvim-colorscheme).
if has('macunix') && !has('macvim_skip_colorscheme')
    let macvim_skip_colorscheme = 1
endif

" default guioptions="egmrLtT" (see :help guioptions for descriptions)
" must remove one at a time (-= to remove, += to add)
if has('menu')
    set guioptions-=M  " hide menu (don't source $VIMRUNTIME/menu.vim)
    set guioptions-=m  " hide menu bar
endif

if has("toolbar")
    set guioptions-=T  " hide toolbar
endif

set lines=38 columns=90

if has('macunix')
    set macligatures
    set guifont=Fira_Code:h16
elseif has('unix')
    set guifont=Ubuntu\ Mono\ 12
else
    set guifont=Roboto_Mono:h10:cANSI
endif

" bright foreground for dark colorschemes
set background=dark

" other great options:
"     torte,desert,solarized,darkblue,badwolf,asu1dark,lucius,obsidian,dosbox-black
colorscheme torte

if &background == 'light'
    hi normal gui=none guifg=black guibg=white
    hi cursorline gui=none guibg=darkblue
else
    hi normal gui=none guifg=white guibg=black
    hi cursorline gui=none guibg=darkblue
    hi search gui=none guifg=fg guibg=DeepSkyBlue4
    hi incsearch gui=bold guifg=fg guibg=DeepSkyBlue4
    hi cursearch gui=bold guifg=fg guibg=DeepSkyBlue4

    if has('visual')
        hi visual guibg=grey
    endif

    " really dark red (R=32h G=00h B=00h)
    hi colorcolumn guifg=fg guibg=#320000
endif

if has('vertsplit')
    hi vertsplit guibg=DeepSkyBlue4
endif

if has('spell')
    " Word not recognized
    hi clear SpellBad
    hi SpellBad gui=undercurl,bold guifg=black guibg=white
    "hi SpellBad gui=underline guifg=lightblue

    " Word not capitalized
    hi clear SpellCap
    hi SpellCap gui=undercurl,bold guifg=red guibg=yellow
    "hi SpellCap gui=underline guifg=red

    " Word is rare
    hi clear SpellRare
    hi SpellRare gui=undercurl,bold guifg=black guibg=green
    "hi SpellRare gui=underline guifg=green

    " Wrong spelling for selected region
    hi clear SpellLocal
    hi SpellLocal gui=undercurl,bold guifg=yellow guibg=blue
    "hi SpellLocal gui=underline guifg=yellow
endif

if has('statusline') && !exists('g:loaded_airline')
    hi statusline guifg=white guibg=DeepSkyBlue4
endif
