" ----------------------------------------------------------------------------
"  ~/vimfiles/gvimrc
"
" config for when gvim is run
"
" Notes:
"     this is a really beautiful color! DeepSkyBlue4=#005f87
" ----------------------------------------------------------------------------

" prevents MacVim from applying its own colorscheme (see :h
" macvim-colorscheme).
if has('macunix') && !has('macvim_skip_colorscheme')
    let macvim_skip_colorscheme = 1
endif

" default guioptions="egmrLtT" (see :help guioptions for descriptions)
" must remove one at a time (-= to remove, += to add)
if has('menu')
    set guioptions-=M  " hide menu (don't source $VIMRUNTIME/menu.vim)
    set guioptions-=m  " hide menu bar
endif

" hide scrollbars
set guioptions-=L  " hide left-hand scrollbar on vert split
set guioptions-=R  " hide right-hand scrollbar on vert split
set guioptions-=b  " hide bottom (horizontal) scrollbar is present
set guioptions-=l  " hide left-hand scrollbar on vert split
set guioptions-=r  " hide right-hand scrollbar

if has('toolbar')
    set guioptions-=T  " hide toolbar
endif

if has('macunix')
    set macligatures
endif

set lines=38 columns=90

if has('unix') || has('macunix')
    "set guifont=IntelOne\ Mono:h16
    "set guifont=Monospace:h10
    set guifont=Ubuntu\ Mono\ 12
else
    set guifont=Roboto\ Mono:h12:cANSI
endif

" bright foreground for dark colorschemes
set background=dark

" other great options:
"     torte,desert,solarized,darkblue,badwolf,asu1dark,lucius,obsidian,dosbox-black
colorscheme torte

if &background == 'light'
    hi normal gui=none guifg=black guibg=white
    hi cursorline gui=none guibg=darkblue
else
    hi normal gui=none guifg=white guibg=black
    hi cursorline gui=none guibg=darkblue
    hi search gui=none guifg=fg guibg=DeepSkyBlue4
    hi incsearch gui=bold guifg=fg guibg=DeepSkyBlue4
    hi cursearch gui=bold guifg=fg guibg=DeepSkyBlue4

    if has('visual')
        hi visual guibg=grey
    endif

    hi colorcolumn guifg=fg guibg=#320000 " really dark red
endif

if has('vertsplit')
    hi vertsplit guibg=DeepSkyBlue4
endif

if has('spell')
    " Word not recognized
    hi clear SpellBad
    hi SpellBad gui=undercurl,bold guifg=black guibg=white

    " Word not capitalized
    hi clear SpellCap
    hi SpellCap gui=undercurl,bold guifg=red guibg=yellow

    " Word is rare
    hi clear SpellRare
    hi SpellRare gui=undercurl,bold guifg=black guibg=green

    " Wrong spelling for selected region
    hi clear SpellLocal
    hi SpellLocal gui=undercurl,bold guifg=yellow guibg=blue
endif

if has('statusline') && !exists('g:loaded_airline')
    hi statusline guifg=white guibg=DeepSkyBlue4
endif
