" ----------------------------------------------------------------------------
"  ~/vimfiles/gvimrc
"
" config for when gvim is run
"
" Notes:
"     this is a really beautiful color! DeepSkyBlue4=#005f87
" ----------------------------------------------------------------------------

" prevents MacVim from applying its own colorscheme (see :h
" macvim-colorscheme).
if has('macunix') && !has('macvim_skip_colorscheme')
    let macvim_skip_colorscheme = 1
endif

" default guioptions="egmrLtT" (see :help guioptions for descriptions)
" must remove one at a time (-= to remove, += to add)
if has('menu')
    set guioptions-=M  " hide menu (don't source $VIMRUNTIME/menu.vim)
    set guioptions-=m  " hide menu bar
endif

if has("toolbar")
    set guioptions-=T  " hide toolbar
endif

" hide scrollbars
set guioptions-=L  " hide left-hand scrollbar on vert split
set guioptions-=R  " hide right-hand scrollbar on vert split
set guioptions-=b  " hide bottom (horizontal) scrollbar is present
set guioptions-=l  " hide left-hand scrollbar on vert split
set guioptions-=r  " hide right-hand scrollbar

set lines=38 columns=90

if has('macunix')
    set macligatures
    set guifont=Fira_Code:h16
elseif has('unix')
    set guifont=Ubuntu\ Mono\ 12
else
    set guifont=Roboto_Mono:h10:cANSI
endif

" be careful because this will clear any highlighting you've already set,
" so be sure to set any custom highlighting anyplace AFTER this statement
hi clear " reset all highlighting to the defaults

" bright foreground for dark colorschemes
set background=dark

" other great options: lucius and dosbox-black
colorscheme meta5

" do this before customizing colors since this has it's own colors it wants to
" use
if has("syntax") && !exists("g:syntax_on")
    syntax enable
endif

"*****************************************************************************
" CUSTOMIZATION INCLUDING COLOR CHOICES
" see C:\opensource\Vim\vim74\rgb.txt
"*****************************************************************************
hi normal gui=none guifg=grey guibg=black
hi search gui=none guifg=fg guibg=DeepSkyBlue4

if has("syntax")
    set colorcolumn=+2 " sets to &textwidth + 2
    if v:version >= 800
        set cursorlineopt=screenline
    endif
    set cursorline   " horizontal line that follows the cursor
    "set cursorcolumn " vertical line that follows the cursor

    " really dark red (R=32h G=00h B=00h)
    hi colorcolumn guifg=fg guibg=#320000
    hi cursorline gui=none guibg=darkblue
endif

if has("extra_search")
    set hlsearch    " highlight all search results
    set incsearch   " show incremental search results as you type

    hi incsearch gui=bold guifg=fg guibg=DeepSkyBlue4
    hi cursearch gui=bold guifg=fg guibg=DeepSkyBlue4
endif

if has('visual')
    hi visual guifg=black guibg=grey
endif

if has('vertsplit')
    " make the vert split a blank space 0x32 instead of the default "|"
    set fillchars=vert:\ " blank space 0x32
    hi vertsplit gui=none guibg=DeepSkyBlue4
endif

if has('spell')
    " Word not recognized
    hi clear SpellBad
    hi SpellBad gui=undercurl,bold guifg=black guibg=white

    " Word not capitalized
    hi clear SpellCap
    hi SpellCap gui=undercurl,bold guifg=red guibg=yellow

    " Word is rare
    hi clear SpellRare
    hi SpellRare gui=undercurl,bold guifg=black guibg=green

    " Wrong spelling for selected region
    hi clear SpellLocal
    hi SpellLocal gui=undercurl,bold guifg=yellow guibg=blue
endif

" not needed if we are using airline plugin
if has('statusline') && !exists('g:loaded_airline')
    hi statusline guifg=white guibg=DeepSkyBlue4
endif
