#!/bin/zsh

#-----------------------------------------------------------------------
# promptrc
#-----------------------------------------------------------------------

# Enable colors and change prompt:
autoload -U colors && colors

# built in color schemes for prompt
#autoload -U promptinit && promptinit

#RED=$fg[red]
#YELLOW=$fg[yellow]
##GREEN=$fg[green]
#BLUE=$fg[blue]
#MAGENTA=$fg[magenta]
#RESET_COLOR=$reset_color

# list all color schemes
#prompt -p
# adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram
#prompt bigfade red white

#PS1="%B%{$RED%}[%{$YELLOW%}%n%{$GREEN%}@%{$BLUE%}%M %{$MAGENTA%}%~%{$RED%}]%{$RESET_COLOR%}%b "
#PS1="%{$fg[red]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%(5~|%-1~/.../%3~|%4~) %{$reset_color%}%% "

# %F{color} is foreground color
# %K{color} is background color
# %Btext%b = bold
# %Utext%u = underline
# %Stext%s = highlight
# %n = username
# %m = hostname (up to first dot)
# %M = full hostname
# %~ = current working directory
# $# = root indicator (# for root, $ for regular user)
# %D = current date
# %T = current time
# %t = current time in 24-hour format
# %* = current time in 12-hour format
# %d = current directory path
# %c = trailing component of current directory
# %L = current shell level
# %j = number of jobs managed by shell
# example: "SteveMBAirM2:~/zsh$ "
PS1="%F{214}%m%F{015}:%F{039}%~%F{015}%# "

