#!/bin/zsh

#-----------------------------------------------------------------------
# securityrc
#-----------------------------------------------------------------------

#export BW_SESSION=redacted
#export HOMEBREW_GITHUB_API_TOKEN=redacted
